// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9Z-sBPLlgCbF-DytBHCvMCiqVeA2M-qU',
    appId: '1:556993160670:web:484b3387ae407fa05e294f',
    messagingSenderId: '556993160670',
    projectId: 'the-capitalhub',
    authDomain: 'the-capitalhub.firebaseapp.com',
    storageBucket: 'the-capitalhub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYvELjeyXqAlrwvyUoj_L-VkjgMREtgr0',
    appId: '1:556993160670:android:9e6d53a424a20d1e5e294f',
    messagingSenderId: '556993160670',
    projectId: 'the-capitalhub',
    storageBucket: 'the-capitalhub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ726J4yHS5zrFQp9Vi8WeWeIQYnA41c0',
    appId: '1:556993160670:ios:58295754b02dddde5e294f',
    messagingSenderId: '556993160670',
    projectId: 'the-capitalhub',
    storageBucket: 'the-capitalhub.firebasestorage.app',
    androidClientId: '556993160670-424ccv0df9ni0gego7q1gdkpm24elpgf.apps.googleusercontent.com',
    iosBundleId: 'com.capitalhub.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ726J4yHS5zrFQp9Vi8WeWeIQYnA41c0',
    appId: '1:556993160670:ios:38325504123a14255e294f',
    messagingSenderId: '556993160670',
    projectId: 'the-capitalhub',
    storageBucket: 'the-capitalhub.firebasestorage.app',
    androidClientId: '556993160670-424ccv0df9ni0gego7q1gdkpm24elpgf.apps.googleusercontent.com',
    iosBundleId: 'com.example.capitalhubCrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9Z-sBPLlgCbF-DytBHCvMCiqVeA2M-qU',
    appId: '1:556993160670:web:a39f000a7046c2625e294f',
    messagingSenderId: '556993160670',
    projectId: 'the-capitalhub',
    authDomain: 'the-capitalhub.firebaseapp.com',
    storageBucket: 'the-capitalhub.firebasestorage.app',
  );
}
